version: 0.2

env:
  variables:
    testvariable: 'test123'

phases:
  install:
    commands:
      - write-output $ENV:testvariable
      - powershell ./BuildScript/InstallPhase.ps1
  pre_build:
    commands:
  build:
    commands:
      - echo $ENV:CODEBUILD_SRC_DIR
      - echo $ENV:CODEBUILD_SOURCE_VERSION
      - echo $ENV:CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo $ENV:CODEBUILD_INITIATOR
      - echo $ENV:CODEBUILD_BUILD_IMAGE
      - echo $ENV:CODEBUILD_BUILD_ID
      - echo $ENV:CODEBUILD_SOURCE_REPO_URL
      - powershell ./BuildScript/BuildPhase.ps1 -CodeBuildID $ENV:CODEBUILD_BUILD_ID
artifacts:
  files:
    - PowerShell/**/*
  name: WigValidation-$(date +%Y-%m-%d)